USE marid_hotel;
DROP TABLE IF EXISTS customer;


CREATE TABLE CUSTOMER (
  id BIGINT PRIMARY KEY AUTO_INCREMENT
  , name VARCHAR(255) NOT NULL
  , phone_number VARCHAR(255) NOT NULL
)ENGINE = INNODB;