ALTER TABLE ROOM
    ADD FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id),
    ADD FOREIGN KEY (booking_id) REFERENCES BOOKING(id),
    ADD FOREIGN KEY (room_type_id) REFERENCES ROOM_TYPE(id)
;

ALTER TABLE BOOKING
    ADD FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id)
;




